;(function(){var dfltPluginCfg={};var dfltGlobalCfg={"site":"","log":"","logSSL":"","domain":"","secure":false,"pixelPath":"/hit.xiti","disableCookie":false,"cookieSecure":false,"cookieDomain":"","preview":false,"plgs":["Tracker","Campaigns","Clicks","ClientSideUserId","ContextVariables","Cookies","IdentifiedVisitor","InternalSearch","MvTesting","OnSiteAds","Page","SalesTracker","TechClicks","Utils","RichMedia"],"lazyLoadingPath":"","documentLevel":"document","redirect":false,"activateCallbacks":true,"medium":"","ignoreEmptyChapterValue":false,"base64Storage":false};(function(a,f){a.ATInternet=a.ATInternet||{};a.ATInternet.Tracker=a.ATInternet.Tracker||{};a.ATInternet.Tracker.Plugins=a.ATInternet.Tracker.Plugins||{}})(window);
var Utils=function(){function a(d){var k=typeof d;if("object"!==k||null===d)return"string"===k&&(d='"'+d+'"'),String(d);var h,g,b=[],e=d&&d.constructor===Array;for(h in d)d.hasOwnProperty(h)&&(g=d[h],k=typeof g,"function"!==k&&"undefined"!==k&&("string"===k?g='"'+g.replace(/[^\\]"/g,'\\"')+'"':"object"===k&&null!==g&&(g=a(g)),b.push((e?"":'"'+h+'":')+String(g))));return(e?"[":"{")+String(b)+(e?"]":"}")}var f=this;f.cloneSimpleObject=function k(a,g){if("object"!==typeof a||null===a||a instanceof Date)return a;
var b=new a.constructor||a.constructor(),e;for(e in a)a.hasOwnProperty(e)&&(void 0===e||g&&void 0===a[e]||(b[e]=k(a[e])));return b};f.jsonSerialize=function(k){return"undefined"!==typeof JSON&&JSON.stringify?JSON.stringify(k):a(k)};f.jsonParse=function(a){try{if("undefined"!==typeof JSON&&JSON.parse)return JSON.parse(a);var h;h=null===a?a:"string"===typeof a?(new Function("return "+a))():!1;return h}catch(g){return null}};f.arrayIndexOf=function(a,h){return Array.indexOf?a.indexOf(h):function(a){if(null==
this)throw new TypeError;var b=Object(this),e=b.length>>>0;if(0===e)return-1;var c=0;1<arguments.length&&(c=Number(arguments[1]),c!=c?c=0:0!=c&&Infinity!=c&&-Infinity!=c&&(c=(0<c||-1)*Math.floor(Math.abs(c))));if(c>=e)return-1;for(c=0<=c?c:Math.max(e-Math.abs(c),0);c<e;c++)if(c in b&&b[c]===a)return c;return-1}.apply(a,[h])};f.uuid=function(){return{v4:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var h=16*Math.random()|0;return("x"===a?h:h&3|8).toString(16)})},
num:function(a){var h=new Date,g=function(a){a-=100*Math.floor(a/100);return 10>a?"0"+a:a};return g(h.getHours())+""+g(h.getMinutes())+""+g(h.getSeconds())+""+function(a){return Math.floor((9*Math.random()+1)*Math.pow(10,a-1))}(a-6)}}};f.getObjectKeys=function(a){var h=[],g;for(g in a)a.hasOwnProperty(g)&&h.push(g);return h};f.completeFstLevelObj=function(a,h,g){if(a){if(h)for(var b in h)!h.hasOwnProperty(b)||a[b]&&!g||(a[b]=h[b])}else a=h;return a};f.isPreview=function(){return window.navigator&&
"preview"===window.navigator.loadPurpose};f.isPrerender=function(a){var h,g=!1,b=["webkit","ms"];if("prerender"===document.visibilityState)h="visibilitychange";else for(var e=0;e<b.length;e++)"prerender"===document[b[e]+"VisibilityState"]&&(h=b[e]+"visibilitychange");if("undefined"!==typeof h){var c=function(b){a(b);f.removeEvtListener(document,h,c)};f.addEvtListener(document,h,c);g=!0}return g};var l=f.addEvtListener=function(a,h,g){a.addEventListener?a.addEventListener(h,g,!1):a.attachEvent&&a.attachEvent("on"+
h,g)};f.removeEvtListener=function(a,h,g){a.removeEventListener?a.removeEventListener(h,g,!1):a.detachEvent&&a.detachEvent("on"+h,g)};f.loadScript=function(a,h){var g;h=h||function(){};g=document.createElement("script");g.type="text/javascript";g.src=a.url;g.async=!1;g.defer=!1;g.onload=g.onreadystatechange=function(a){a=a||window.event;if("load"===a.type||/loaded|complete/.test(g.readyState)&&(!document.documentMode||9>document.documentMode))g.onload=g.onreadystatechange=g.onerror=null,h(null,a)};
g.onerror=function(a,b,k){g.onload=g.onreadystatechange=g.onerror=null;h({msg:"script not loaded",event:a})};var b=document.head||document.getElementsByTagName("head")[0];b.insertBefore(g,b.lastChild)};f.hashcode=function(a){var h=0;if(0===a.length)return h;for(var g=0;g<a.length;g++)var b=a.charCodeAt(g),h=(h<<5)-h+b,h=h&h;return h};f.setLocation=function(a){var h=a.location;a=window[a.target]||window;h&&(a.location.href=h)};f.dispatchCallbackEvent=function(a){var h=document.createEvent("Event");
h.initEvent("ATCallbackEvent",!0,!0);h.name=a;document.dispatchEvent(h)};f.addCallbackEvent=function(a){document.createEvent("Event").initEvent("ATCallbackEvent",!0,!0);l(document,"ATCallbackEvent",a)}};window.ATInternet.Utils=new Utils;
var BuildManager=function(a){var f=this,l=function(a,b,k){a="&"+a+"=";return{param:a,paramSize:a.length,str:b,strSize:b.length,truncate:k}},d=function(b,c){var k="",d=0,h=!0,m;for(m in b)if(b.hasOwnProperty(m)){var p=b[m];if(p){var h=!1,g=c-d;if(p.strSize+p.paramSize<g)k+=p.param+p.str,d+=p.strSize+p.paramSize,b[m]=void 0,h=!0;else{p.truncate?(k+=p.param+p.str.substr(0,g),b[m].str=p.str.substr(g,p.strSize-1),b[m].strSize=b[m].str.length):p.strSize+p.paramSize>c&&(a.emit("Tracker:Hit:Build:Error",
{lvl:"ERROR",msg:'Too long parameter "'+p.param+'"',details:{value:p.str}}),b[m].str=b[m].str.substr(0,c-p.paramSize-1),b[m].strSize=b[m].str.length);break}}else h=!0}return[k,h?null:b]},k=["ati","atc","pdtl","stc","dz"],h=function(b,c,n){var h=function(a){if(a==={})return"";var b=[],c;c={};var m=0,e=!1,n=void 0,h,g,f;for(f in a)if(a.hasOwnProperty(f)){var q=a[f].value;"function"===typeof q&&(q=q());q=q instanceof Array?q.join(a[f].options.separator||","):"object"===typeof q?window.ATInternet.Utils.jsonSerialize(q):
"undefined"===typeof q?"undefined":q.toString();a[f].options.encode&&(q=encodeURIComponent(q));var s=l(f,q,-1<window.ATInternet.Utils.arrayIndexOf(k,f)),m=m+(s.paramSize+s.strSize);if(a[f].options.last)1490<q.length&&q.substr(0,1490),h=f,g=s;else if(c[f]=s,1500<c[f].paramSize+c[f].strSize&&!c[f].truncate){e=!0;n=f;break}}h&&(c[h]=g);c=[c,m,e,n];a=c[0];if(c[2])c=c[3],a=a[c],a.str=a.str.substr(0,1450),a.strSize=1450,m={},m.mherr=l("mherr","1",!1),m[c]=a,b.push(d(m,1500)[0]);else if(c=d(a,1500),null===
c[1])b=c[0];else for(b.push(c[0]);null!==c[1];)c=d(a,1500),b.push(c[0]);return b},g="";a.buffer.presentInFilters(c,"hitType")||(c=a.buffer.addInFilters(c,"hitType",["page"]));c=a.buffer.addInFilters(c,"hitType",["all"]);var m;if(b){c=a.buffer.addInFilters(c,"permanent",!0);c=a.buffer.get(c,!0);for(m in b)b.hasOwnProperty(m)&&(c[m]={value:b[m],options:{}});g=h(c)}else for(m in c=a.buffer.get(c,!0),g=h(c),c)c.hasOwnProperty(m)&&!c[m].options.permanent&&a.buffer.del(m);n&&n(g)},g=function(b){var c=a.getConfig("secure"),
k="https:"===document.location.protocol,k=c||k?a.getConfig("logSSL"):a.getConfig("log"),h=a.getConfig("baseURL"),g=a.getConfig("domain"),m=a.getConfig("pixelPath"),p=a.getConfig("site");(h||k&&g&&m)&&p?b&&b(null,(h?h:(c?"https://":"//")+k+("."+g)+m)+("?s="+p)):b&&b({message:"Config error"})},b=function(a,b,k){g(function(g,d){g?k&&k(g):h(a,b,function(a){var b=[],c=ATInternet.Utils.uuid().num(13);if(a instanceof Array)if(1===a.length)b.push(d+"&mh=1-2-"+c+a[0]);else for(var e=1;e<=a.length;e++)b.push(d+
"&mh="+e+"-"+a.length+"-"+c+a[e-1]);else b.push(d+a);k&&k(null,b)})})};f.send=function(e,c){b(e,c,function(b,c){if(b)a.emit("Tracker:Hit:Build:Error",{lvl:"ERROR",msg:b.message,details:{hits:c}});else for(var e=0;e<c.length;e++)f.sendUrl(c[e])})};f.sendUrl=function(b){var c=function(b,c){return function(){return function(m){a.emit(b,{lvl:-1===b.indexOf("Error")?"INFO":"ERROR",details:{hit:c,event:m}})}}()},k=new Image;k.onload=c("Tracker:Hit:Sent:Ok",b);k.onerror=c("Tracker:Hit:Sent:Error",b);k.src=
b}},TriggersManager=function(){function a(a,h,g){for(var b=[],e=0;e<a.length;e++)a[e].callback(h,g),a[e].singleUse||b.push(a[e]);return b}function f(a,h,g,b){var e=a.shift();if("*"===e)return h["*"]=h["*"]||[],h["*"].push({callback:g,singleUse:b}),h["*"].length-1;if(0===a.length)return f([e,"*"],h,g,b);h["*"]=h["*"]||[];h[e]=h[e]||{};return f(a,h[e],g,b)}function l(k,h,g,b){var e=h.shift();"*"!==e&&(0===h.length?l(k,[e,"*"],g,b):g[e]&&(g[e]["*"]=a(g[e]["*"],k,b),l(k,h,g[e],b)))}var d={};this.on=function(a,
h,g){g=g||!1;return f(a.split(":"),d,h,g)};this.emit=function(k,h){d["*"]&&(d["*"]=a(d["*"],k,h));l(k,k.split(":"),d,h)}},PluginsManager=function(a){var f={},l={},d=0,k={},h=0,g=this.load=function(c,e){"function"===typeof e?"undefined"===typeof a.getConfig.plgAllowed||0===a.getConfig.plgAllowed.length||-1<a.getConfig.plgAllowed.indexOf(c)?(f[c]=new e(a),l[c]&&f[c]&&(l[c]=!1,d--,f[c+"_ll"]&&b(c+"_ll"),0===d&&a.emit("Tracker:Plugin:Lazyload:File:Complete",{lvl:"INFO",msg:"LazyLoading triggers are finished"})),
a.emit("Tracker:Plugin:Load:"+c+":Ok",{lvl:"INFO"})):a.emit("Tracker:Plugin:Load:"+c+":Error",{lvl:"ERROR",msg:"Plugin not allowed",details:{}}):a.emit("Tracker:Plugin:Load:"+c+":Error",{lvl:"ERROR",msg:"not a function",details:{obj:e}});return a},b=this.unload=function(b){f[b]?(f[b]=void 0,a.emit("Tracker:Plugin:Unload:"+b+":Ok",{lvl:"INFO"})):a.emit("Tracker:Plugin:Unload:"+b+":Error",{lvl:"ERROR",msg:"not a known plugin"});return a},e=this.isLazyloading=function(a){return a?!0===l[a]:0!==d},c=
function(a){return s(a)?(n(a),!0):!1},n=function(b){l[b]=!0;d++;ATInternet.Utils.loadScript({url:a.getConfig("lazyLoadingPath")+b+".js"})},s=function(a){return!f[a]&&!e(a)&&(f[a+"_ll"]?!0:!1)},q=function(a){k[a]?k[a]++:k[a]=1;h++};this.isExecWaitingLazyloading=function(){return 0!==h};a.exec=this.exec=function(b,c,g,d){var l=null,r=function(a,b,c,e){b=b.split(".");f[a]&&f[a][b[0]]&&(l=1<b.length&&f[a][b[0]][b[1]]?f[a][b[0]][b[1]].apply(f[a],c):f[a][b[0]].apply(f[a],c));e&&e(l)},v=function(b,c,e,p){q(b);
a.onTrigger("Tracker:Plugin:Load:"+b+":Ok",function(){r(b,c,e,function(c){k[b]--;h--;0===h&&a.emit("Tracker:Plugin:Lazyload:Exec:Complete",{lvl:"INFO",msg:"All exec waiting for lazyloading are done"});p&&p(c)})},!0)};s(b)?(v(b,c,g,d),n(b)):e(b)?v(b,c,g,d):r(b,c,g,d)};this.waitForDependencies=function(b,e){var k=function(a){for(var b={mcount:0,plugins:{}},c=0;c<a.length;c++)f.hasOwnProperty(a[c])||(b.mcount++,b.plugins[a[c]]=!0);return b}(b);if(0===k.mcount)a.emit("Tracker:Plugin:Dependencies:Loaded",
{lvl:"INFO",details:{dependencies:b}}),e();else for(var g in k.plugins)k.plugins.hasOwnProperty(g)&&(a.emit("Tracker:Plugin:Dependencies:Error",{lvl:"WARNING",msg:"Missing plugin "+g}),a.onTrigger("Tracker:Plugin:Load:"+g,function(a,b){var c=a.split(":"),g=c[3];"Ok"===c[4]&&(k.plugins[g]=!1,k.mcount--,0===k.mcount&&e())},!0),c(g))};this.init=function(){for(var a in ATInternet.Tracker.pluginProtos)ATInternet.Tracker.pluginProtos.hasOwnProperty(a)&&g(a,ATInternet.Tracker.pluginProtos[a])}},CallbacksManager=
function(a){var f={};this.init=function(){if(a.getConfig("activateCallbacks")){var d=a.getConfig("callbacks");(function(){if("undefined"!==typeof d&&d.include instanceof Array)for(var a=0;a<d.include.length;a++)ATInternet.Callbacks&&ATInternet.Callbacks.hasOwnProperty(d.include[a])&&(f[d.include[a]]={"function":ATInternet.Callbacks[d.include[a]]},ATInternet.Tracker.callbackProtos[d.include[a]]||(ATInternet.Tracker.callbackProtos[d.include[a]]=f[d.include[a]]));else for(a in ATInternet.Callbacks)ATInternet.Callbacks.hasOwnProperty(a)&&
(f[a]={"function":ATInternet.Callbacks[a]},ATInternet.Tracker.callbackProtos[a]||(ATInternet.Tracker.callbackProtos[a]=f[a]));if("undefined"!==typeof d&&d.exclude instanceof Array)for(a=0;a<d.exclude.length;a++)f[d.exclude[a]]&&(f[d.exclude[a]]=void 0);for(var h in f)f.hasOwnProperty(h)&&f[h]&&l(h,f[h]["function"])})();ATInternet.Utils.addCallbackEvent(function(a){if(a.name){var h=!0;"undefined"!==typeof d&&(d.include instanceof Array&&-1===ATInternet.Utils.arrayIndexOf(d.include,a.name)&&(h=!1),
d.exclude instanceof Array&&-1!==ATInternet.Utils.arrayIndexOf(d.exclude,a.name)&&(h=!1));if(ATInternet.Callbacks&&ATInternet.Callbacks.hasOwnProperty(a.name)){var g={};g[a.name]={"function":ATInternet.Callbacks[a.name]};h&&l(a.name,g[a.name]["function"]);ATInternet.Tracker.callbackProtos[a.name]||(ATInternet.Tracker.callbackProtos[a.name]=g[a.name])}}})}};var l=this.load=function(d,k){"function"===typeof k?(new k(a),a.emit("Tracker:Callback:Load:"+d+":Ok",{lvl:"INFO",details:{obj:k}})):a.emit("Tracker:Callback:Load:"+
d+":Error",{lvl:"ERROR",msg:"not a function",details:{obj:k}});return a}},BufferManager=function(a){var f={};this.set=function(a,h,g){g=g||{};g.hitType=g.hitType||["page"];f[a]={value:h,options:g}};var l=function(a,h,g){return(a=window.ATInternet.Utils.cloneSimpleObject(a[h]))&&!g?a.value:a},d=function h(a,b){if(!(a&&b instanceof Array&&a instanceof Array))return[];if(0===a.length)return b;var e=a[0],c,d=[],l=window.ATInternet.Utils.cloneSimpleObject(a);l.shift();for(var q=0;q<b.length;q++)if("object"!==
typeof e[1])f[b[q]]&&f[b[q]].options[e[0]]===e[1]&&d.push(b[q]);else{c=e[1].length;for(var m=0;m<c;m++)if(f[b[q]]&&f[b[q]].options[e[0]]instanceof Array&&0<=window.ATInternet.Utils.arrayIndexOf(f[b[q]].options[e[0]],e[1][m])){d.push(b[q]);break}}return h(l,d)};this.get=function(a,g){var b={};if("string"===typeof a)b=l(f,a,g);else for(var e=d(a,window.ATInternet.Utils.getObjectKeys(f)),c=0;c<e.length;c++)b[e[c]]=l(f,e[c],g);return b};this.presentInFilters=function g(a,e){return a&&0!==a.length?a[0][0]===
e?!0:g(a.slice(1),e):!1};this.addInFilters=function b(a,c,d,f){if(!a||0===a.length)return f?[]:[[c,d]];var q=a[0][0],m=a[0][1];q===c&&(m instanceof Array&&!(-1<window.ATInternet.Utils.arrayIndexOf(m,d[0]))&&m.push(d[0]),f=!0);return[[q,m]].concat(b(a.slice(1),c,d,f))};this.del=function(a){f[a]=void 0};this.clear=function(){f={}}},Tag=function(a,f,l){f=f||{};var d=this;d.version="5.8.0";var k=window.ATInternet.Utils.cloneSimpleObject(f);d.triggers=new TriggersManager(d);d.emit=d.triggers.emit;d.onTrigger=
d.triggers.on;var h=window.ATInternet.Utils.cloneSimpleObject(dfltGlobalCfg)||{},g;for(g in a)a.hasOwnProperty(g)&&(h[g]=a[g]);d.getConfig=function(a){return h[a]};d.setConfig=function(a,e,c){void 0!==h[a]&&c||(d.emit("Tracker:Config:Set:"+a,{lvl:"INFO",details:{bef:h[a],aft:e}}),h[a]=e)};d.configPlugin=function(a,e,c){h[a]=h[a]||{};for(var g in e)e.hasOwnProperty(g)&&void 0===h[a][g]&&(h[a][g]=e[g]);c&&(c(h[a]),d.onTrigger("Tracker:Config:Set:"+a,function(a,b){c(b.details.aft)}));return h[a]};d.getContext=
function(a){return k[a]};d.setContext=function(a,e){d.emit("Tracker:Context:Set:"+a,{lvl:"INFO",details:{bef:k[a],aft:e}});k[a]=e};d.delContext=function(a,e){d.emit("Tracker:Context:Deleted:"+a+":"+e,{lvl:"INFO",details:{key1:a,key2:e}});if(a)k.hasOwnProperty(a)&&(e?k[a]&&k[a].hasOwnProperty(e)&&(k[a][e]=void 0):k[a]=void 0);else if(e)for(var c in k)k.hasOwnProperty(c)&&k[c]&&k[c].hasOwnProperty(e)&&(k[c][e]=void 0)};d.plugins=new PluginsManager(d);d.buffer=new BufferManager(d);d.setParam=d.buffer.set;
d.getParams=function(a){return d.buffer.get(a,!1)};d.getParam=d.buffer.get;d.delParam=d.buffer.del;d.builder=new BuildManager(d);d.sendHit=d.builder.send;d.sendUrl=d.builder.sendUrl;d.callbacks=new CallbacksManager(d);d.setParam("ts",function(){return(new Date).getTime()},{permanent:!0,hitType:["all"]});d.getConfig("disableCookie")&&d.setParam("idclient","xxxxxx-NO",{permanent:!0,hitType:["all"]});d.getConfig("medium")&&d.setParam("medium",d.getConfig("medium"),{permanent:!0,hitType:["all"]});d.plugins.init();
d.callbacks.init();ATInternet.Tracker.instances.push(d);d.emit("Tracker:Ready",{lvl:"INFO",msg:"Tracker initialized",details:{tracker:d,args:{config:a,context:f,callback:l}}});l&&l(d)};ATInternet.Tracker.Tag=Tag;ATInternet.Tracker.instances=[];ATInternet.Tracker.pluginProtos={};
ATInternet.Tracker.addPlugin=function(a,f){f=f||ATInternet.Tracker.Plugins[a];if(!ATInternet.Tracker.pluginProtos[a]){ATInternet.Tracker.pluginProtos[a]=f;for(var l=0;l<ATInternet.Tracker.instances.length;l++)ATInternet.Tracker.instances[l].plugins.load(a,f)}};ATInternet.Tracker.delPlugin=function(a){if(ATInternet.Tracker.pluginProtos[a]){ATInternet.Tracker.pluginProtos[a]=void 0;for(var f=0;f<ATInternet.Tracker.instances.length;f++)ATInternet.Tracker.instances[f].plugins.unload(a)}};
ATInternet.Tracker.callbackProtos={};
}).call(window);;(function(){var dfltPluginCfg={"lifetime":30,"lastPersistence":true,"listEventsForExec":[],"domainAttribution":true};var dfltGlobalCfg={"visitLifetime":30,"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.Campaigns=function(a){a.setConfig("visitLifetime",dfltGlobalCfg.visitLifetime,!0);a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var f={},l,d;a.configPlugin("Campaigns",dfltPluginCfg||{},function(a){f=a});var k,h,g,b,e,c,n,s,q,m,p,u,z,y=function(b,c,e){var g=null;a.plugins.exec(b,c,e,function(a){g=a});return g},r=function(a,b){return y("Cookies",a,b)},v=function(a,b){return y("Utils",a,b)},x=function(a,b){var c=r(d,[a]);if(null!==c)return"object"===
typeof c&&!(c instanceof Array);r(l,[a,{},b]);return!0},A=function(b,c){var e=a.getContext("campaigns")||{};e[b]=c;a.setContext("campaigns",e)},w=function(y){l="set"+(f.domainAttribution?"":"Private");d="get"+(f.domainAttribution?"":"Private");k=r(d,[["atredir","gopc"]]);h=r(d,[["atredir","gopc_err"]]);g=r(d,[["atredir","camp"]]);r("del",[["atredir","gopc"]]);r("del",[["atredir","gopc_err"]]);r("del",[["atredir","camp"]]);b=r(d,[["atsession","histo_camp"]]);e=r(d,[["atreman","camp"]]);c=r(d,[["atreman",
"date"]]);var t=v("getLocation",[]);n=v("getQueryStringValue",["xtor",t]);s=v("getQueryStringValue",["xtdt",t]);q=v("getQueryStringValue",["xts",t]);m=a.getContext("forcedCampaign");p=!!a.getConfig("redirect");if(u=n&&s&&q?!0:!1)t=(new Date).getTime()/6E4,z=!p&&q!==a.getConfig("site")||0>t-s||t-s>=a.getConfig("visitLifetime")?!0:!1;t=m||g||n;p&&t&&x("atredir",{path:"/",end:a.getConfig("redirectionLifetime")})&&(r(l,[["atredir","camp"],t]),r(l,[["atredir","gopc"],m?!1:g?k:u?!0:!1]),r(l,[["atredir",
"gopc_err"],m?!1:g?h:z?!0:!1]));!p&&e&&(A("xtor",e),t=(new Date).getTime()/36E5,t=Math.floor(t-c),A("roinbh",0<=t?t:0));p||(t=void 0,t=g?k?m||t:m||g:u?m||t:m||n||t,b&&b instanceof Array&&-1<b.indexOf(t)&&(t=void 0),t&&A("xto",t));if(!p&&!m){var w;g?h&&(w=g):z&&(w=n);w&&A("pgt",w)}p||!(w=g?m||g:m||n||void 0)||!m&&!g&&u&&z||!m&&g&&k&&h||((!b||b instanceof Array&&0>b.indexOf(w))&&x("atsession",{path:"/",session:60*a.getConfig("visitLifetime")})&&r(l,[["atsession","histo_camp"],b&&b.push(w)?b:[w]]),e&&
!f.lastPersistence||!x("atreman",{path:"/",session:86400*f.lifetime})||(r(l,[["atreman","camp"],w]),r(l,[["atreman","date"],(new Date).getTime()/36E5])));a.emit("Campaigns:"+y,{lvl:"INFO"})};(function(){var b=["Cookies","Utils"];if(-1===ATInternet.Utils.arrayIndexOf(a.getConfig("plgs"),"BackwardCompat"))a.plugins.waitForDependencies(b,function(){w("process2:done")});else a.onTrigger("BackCampaigns:process2:done",function(c,e){a.plugins.waitForDependencies(b,function(){w("process1:done")})},!0)})()};
window.ATInternet.Tracker.addPlugin("Campaigns");
}).call(window);;(function(){var dfltPluginCfg={};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Clicks=function(a){var f=function(a){var d="";switch(a){case "exit":d="S";break;case "download":d="T";break;case "action":d="A";break;case "navigation":d="N"}return d},l=function(d){var h=d.name;a.exec("Utils","manageChapters",[d,"chapter",3],function(a){h=a+(h?h:"")});return h},d=function(d){var h={p:l(d),s2:d.level2||"",click:f(d.type)||""},g=a.getContext("page")||{};h.pclick=l(g);h.s2click=g.level2||"";d.customObject&&a.exec("Utils","customObjectToString",[d.customObject],
function(a){h.stc=a});a.sendHit(h,[["hitType",["click"]]])};a.click={};a.clickListener=this.clickListener={};a.click.send=this.send=function(k){var h=!0;a.plugins.exec("TechClicks","manageClick",[k.elem,k.event,k.callback],function(a){h=a});d(k);return h};a.clickListener.send=this.clickListener.send=function(k){if(k.elem){var h;a.plugins.exec("TechClicks","isFormSubmit",[k.elem],function(a){h=a?"submit":"click"});ATInternet.Utils.addEvtListener(k.elem,h,function(g){a.plugins.exec("TechClicks","manageClick",
[k.elem,g,k.callback]);d(k)})}};a.click.set=this.set=function(d){a.dispatchSubscribe("click");a.setContext("click",{name:l(d),level2:d.level2||"",customObject:d.customObject});a.setParam("click",f(d.type)||"",{hitType:["click"]})};a.click.onDispatch=this.onDispatch=function(){var d={hitType:["click"]};a.setParam("p",a.getContext("click").name,d);a.setParam("s2",a.getContext("click").level2,d);var h=a.getContext("click").customObject;h&&a.setParam("stc",h,{hitType:["click"],encode:!0});h=a.getContext("page")||
{};a.setParam("pclick",l(h),d);a.setParam("s2click",h.level2||"",d);a.sendHit(null,[["hitType",["click"]]]);a.setContext("click",void 0)}};window.ATInternet.Tracker.addPlugin("Clicks");
}).call(window);;(function(){var dfltPluginCfg={"clientSideMode":"required","userIdCookieDuration":397,"userIdExpirationMode":"fixed"};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.ClientSideUserId=function(a){var f={},l=void 0,d=null;a.configPlugin("ClientSideUserId",dfltPluginCfg||{},function(a){f=a});var k=function(){l=a.getContext("userIdentifier");a.exec("Cookies","get",["atuserid"],function(a){d=a})},h=function(b,c){a.setParam("idclient",b,{permanent:!0,hitType:["all"]});g(b,c)},g=function(b,c){if("relative"===f.userIdExpirationMode||"fixed"===f.userIdExpirationMode&&null===d){var g=new Date;g.setTime(g.getTime()+864E5*f.userIdCookieDuration);
a.exec("Cookies","set",["atuserid",b,{end:g,path:"/"}]);a.exec("Cookies","get",["atuserid",!0],function(d){c||b===d||a.setParam("idclient",b+"-NO",{permanent:!0,hitType:["all"]})})}},b=function(){var a=!1;if("required"===f.clientSideMode){var b=navigator.userAgent;if(/Safari/.test(b)&&!/Chrome/.test(b)||/iPhone|iPod|iPad/.test(b))a=!0}else"always"===f.clientSideMode&&(a=!0);return a};a.plugins.waitForDependencies(["Cookies"],function(){k();var e="";if(b()){var c=!1;"undefined"!==typeof l?(e=l,c=!0):
e=null!==d?d:ATInternet.Utils.uuid().v4();h(e,c)}a.emit("ClientSideUserId:Ready",{lvl:"INFO",details:{clientSideMode:f.clientSideMode,userIdFromContext:l,userIdFromCookie:d,userId:e}})});a.clientSideUserId={};a.clientSideUserId.set=function(a){b()&&h(a,!0)}};window.ATInternet.Tracker.addPlugin("ClientSideUserId");
}).call(window);;(function(){var dfltPluginCfg={"domainAttribution":true};var dfltGlobalCfg={"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.ContextVariables=function(a){var f="",l=null,d,k="",h="",g={};a.configPlugin("ContextVariables",dfltPluginCfg||{},function(a){g=a});a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var b=function(b,c,e){var d=null;a.plugins.exec(b,c,e,function(a){d=a});return d},e=function(a,c){return b("Utils",a,c)},c=function(b,c){var e=null;a.plugins.exec("Cookies",b,c,function(a){e=a});return e},n=function(){a.setParam("hl",function(){var a=new Date;return a.getHours()+
"x"+a.getMinutes()+"x"+a.getSeconds()},{permanent:!0,hitType:["all"]})},s=function(a){var b="",b=d?d:"acc_dir"===f?"":null!=f?f:"acc_dir"===l?"":l?l:a.referrer;return b.replace(/[<>]/g,"").substring(0,1600).replace(/&/g,"$")};a.plugins.waitForDependencies(["Cookies","Utils"],function(){k="set"+(g.domainAttribution?"":"Private");h="get"+(g.domainAttribution?"":"Private");var b=e("getLocation",[]);f=e("getQueryStringValue",["xtref",b]);void 0===f&&(f="");d=a.getContext("forcedReferer");if(a.getConfig("redirect")){var b=
e("getDocumentLevel",[]),b=d?d:null!=f?f:b.referrer||"acc_dir",m;if(m=b){m={path:"/",end:a.getConfig("redirectionLifetime")};var p=c(h,["atredir"]);null!==p?m="object"===typeof p&&!(p instanceof Array):(c(k,["atredir",{},m]),m=!0)}m&&c(k,[["atredir","ref"],b])}else{l=c(h,[["atredir","ref"]]);c("del",[["atredir","ref"]]);a.setParam("vtag",a.version,{permanent:!0,hitType:["all"]});a.setParam("ptag","js",{permanent:!0,hitType:["all"]});b="";try{b+=window.screen.width+"x"+window.screen.height+"x"+window.screen.pixelDepth+
"x"+window.screen.colorDepth}catch(u){}a.setParam("r",b,{permanent:!0,hitType:["all"]});b="";window.innerWidth?b+=window.innerWidth+"x"+window.innerHeight:document.body&&document.body.offsetWidth&&(b+=document.body.offsetWidth+"x"+document.body.offsetHeight);a.setParam("re",b,{permanent:!0,hitType:["all"]});n();a.setParam("lng",navigator.language||navigator.userLanguage,{permanent:!0,hitType:["all"]});b=ATInternet.Utils.uuid().num(13);a.setParam("idp",b,{permanent:!0,hitType:["page","clickzone"]});
a.setParam("jv",navigator.javaEnabled()?"1":"0",{hitType:["page"]});b=e("getDocumentLevel",[]);a.setParam("ref",s(b),{permanent:!0,last:!0,hitType:["page"]})}a.emit("ContextVariables:Ready",{lvl:"INFO"})})};window.ATInternet.Tracker.addPlugin("ContextVariables");
}).call(window);;(function(){var dfltPluginCfg={};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Cookies=function(a){var f={},l={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(a){var b="",c,e,d,g,h,f,n=0;for(a=l._utf8_encode(a);n<a.length;)c=a.charCodeAt(n++),e=a.charCodeAt(n++),d=a.charCodeAt(n++),g=c>>2,c=(c&3)<<4|e>>4,h=(e&15)<<2|d>>6,f=d&63,isNaN(e)?h=f=64:isNaN(d)&&(f=64),b=b+this._keyStr.charAt(g)+this._keyStr.charAt(c)+this._keyStr.charAt(h)+this._keyStr.charAt(f);return b},decode:function(a){var b="",c,e,d,
g,h,f=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");f<a.length;)c=this._keyStr.indexOf(a.charAt(f++)),e=this._keyStr.indexOf(a.charAt(f++)),g=this._keyStr.indexOf(a.charAt(f++)),h=this._keyStr.indexOf(a.charAt(f++)),c=c<<2|e>>4,e=(e&15)<<4|g>>2,d=(g&3)<<6|h,b+=String.fromCharCode(c),64!=g&&(b+=String.fromCharCode(e)),64!=h&&(b+=String.fromCharCode(d));return b=l._utf8_decode(b)},_utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var b="",c=0;c<a.length;c++){var e=a.charCodeAt(c);128>e?b+=String.fromCharCode(e):
(127<e&&2048>e?b+=String.fromCharCode(e>>6|192):(b+=String.fromCharCode(e>>12|224),b+=String.fromCharCode(e>>6&63|128)),b+=String.fromCharCode(e&63|128))}return b},_utf8_decode:function(a){for(var b="",c=0,e,d,g;c<a.length;)e=a.charCodeAt(c),128>e?(b+=String.fromCharCode(e),c++):191<e&&224>e?(d=a.charCodeAt(c+1),b+=String.fromCharCode((e&31)<<6|d&63),c+=2):(d=a.charCodeAt(c+1),g=a.charCodeAt(c+2),b+=String.fromCharCode((e&15)<<12|(d&63)<<6|g&63),c+=3);return b}},d=this.getCookie=function(b){return!a.getConfig("disableCookie")&&
b&&"string"===typeof b&&(b=RegExp("(?:^| )"+b+"=([^;]+)").exec(document.cookie)||null)?(b=b[1],b=a.getConfig("base64Storage")?l.decode(b):decodeURIComponent(b),b):null},k=this.setCookie=function(b,c,e){if(!a.getConfig("disableCookie")&&b&&"string"===typeof b&&"string"===typeof c){var d=a.getConfig("cookieDomain");b+="=";c=a.getConfig("base64Storage")?l.encode(c):encodeURIComponent(c);c=b+c;b=!1;if(e){b=e.secure;var g=e.end,h=e.domain;e=e.path;c+=g?"function"===typeof g.toGMTString?";expires="+g.toGMTString():
"number"===typeof g?";max-age="+g.toString():"":"";c=c+(d||h?";domain="+(h?h:d):"")+(e&&"string"===typeof e?";path="+e:"")}d=a.getConfig("cookieSecure")||b;c+=d&&"boolean"===typeof d?";secure":"";document.cookie=c;return!0}return null},h=function(a){var b=null;(a=d(a))&&(b=ATInternet.Utils.jsonParse(a));return b},g=function(a){return k(a.name,ATInternet.Utils.jsonSerialize(a),a.options)?a:null},b=function(a,b,c){var e=null;if(!c&&f[a])e=f[a];else if(e=h(a))e.options.session&&g(e),f[a]=e;return e?
b?(a=null,!e||"object"!==typeof e.val||e.val instanceof Array||void 0===e.val[b]||(a=e.val[b]),a):e.val:null},e=function(a,b,c,e){var d=null;if(b){if(d=h(a))e=d,!e||"object"!==typeof e.val||e.val instanceof Array?d=null:(e.val[b]=c,d=e),d&&(d=g(d))}else b=e=e||{},e={},e.name=a,e.val=c,b.session&&"number"===typeof b.session&&(b.end=b.session),e.options=b,d=g(e);d&&(f[a]=d);return d?d.val:null},c=function(a,b){b?e(a,b,void 0):(f[a]=void 0,k(a,"",{end:0}))},n=this.get=function(a,c){c=c||!1;return a instanceof
Array&&2===a.length?b(a[0],a[1],c):b(a,void 0,c)};this.getPrivate=function(b,c){c=c||!1;b instanceof Array?b[0]+=a.getConfig("site"):b+=a.getConfig("site");return n(b,c)};var s=this.set=function(a,b,c){return a instanceof Array?e(a[0],a[1],b):e(a,null,b,c)};this.setPrivate=function(b,c,e){b instanceof Array?b[0]+=a.getConfig("site"):b+=a.getConfig("site");return s(b,c,e)};var q=this.del=function(a){return a instanceof Array?c(a[0],a[1]):c(a)};this.delPrivate=function(b){b instanceof Array?b[0]+=a.getConfig("site"):
b+=a.getConfig("site");return q(b)};this.cacheInvalidation=function(){f={}}};window.ATInternet.Tracker.addPlugin("Cookies");
}).call(window);;(function(){var dfltPluginCfg={"lifetime":182,"domainAttribution":true};var dfltGlobalCfg={"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.IdentifiedVisitor=function(a){var f=null,l=null,d=null,k=null,h="",g="",b=null,e=null,c="",n="",s={};a.configPlugin("IdentifiedVisitor",dfltPluginCfg||{},function(a){s=a});a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var q=function(b,c,e){var d=null;a.plugins.exec(b,c,e,function(a){d=a});return d},m=function(a,b){return q("Utils",a,b)},p=function(b,c){var e=null;a.plugins.exec("Cookies",b,c,function(a){e=a});return e},u=function(a,b){var e=
p(n,[a]);if(null!==e)return"object"===typeof e&&!(e instanceof Array);p(c,[a,{},b]);return!0},z=function(){var c=function(a,b){/-/.test(b)?(a.category=b.split("-")[0],a.id=b.split("-")[1]):a.id=b},n={category:"",id:""};c(n,g||e);var k={category:"",id:""};c(k,h||b);k.id?(k.category&&r("ac",k.category),r("at",k.id)):f&&a.setParam("at",f,{hitType:["all"],permanent:!0});n.id?(n.category&&r("ac",n.category),r("an",n.id)):l&&a.setParam("anc",d+"-"+l,{hitType:["all"],permanent:!0})},y=function(a,b){u("atidvisitor",
{path:"/",session:86400*s.lifetime})&&p(c,[["atidvisitor",a],b])},r=function(b,c){a.setParam(b,c,{hitType:["all"],permanent:!0});y(b,c)};a.plugins.waitForDependencies(["Cookies","Utils"],function(){c="set"+(s.domainAttribution?"":"Private");n="get"+(s.domainAttribution?"":"Private");var q=m("getLocation",[]);h=m("getQueryStringValue",["xtat",q]);g=m("getQueryStringValue",["xtan",q]);a.getConfig("redirect")?(h||g)&&u("atredir",{path:"/",end:a.getConfig("redirectionLifetime")})&&(g&&p(c,[["atredir",
"an"],g]),h&&p(c,[["atredir","at"],h])):(b=p(n,[["atredir","at"]]),e=p(n,[["atredir","an"]]),p("del",[["atredir","at"]]),p("del",[["atredir","an"]]),f=p(n,[["atidvisitor","at"]]),l=p(n,[["atidvisitor","an"]]),d=p(n,[["atidvisitor","ac"]]),k=p(n,[["atidvisitor","vrn"]]),z(),q="-"+a.getConfig("site")+"-",RegExp(q).test(k)||(k=(k||"")+q,y("vrn",k),q=a.getContext("page")||{},q.vrn=1,a.setContext("page",q)));a.emit("IdentifiedVisitor:Ready",{lvl:"INFO",details:{cookieRedirectTextual:b,cookieRedirectNumeric:e,
cookieTextual:f,cookieNumeric:l,cookieCategory:d,cookieVrn:k}})});a.identifiedVisitor={};a.identifiedVisitor.set=this.set=function(a){var b=a.id;a=a.category;"number"===typeof b?r("an",b.toString()):r("at",b);"undefined"!==typeof a&&r("ac",a)};a.identifiedVisitor.unset=this.unset=function(){for(var b=["an","at","ac"],c=0;c<b.length;c++)a.exec("Cookies","set",[["atidvisitor",b[c],{path:"/"}],void 0]),a.delParam(b[c]);a.delParam("anc")}};window.ATInternet.Tracker.addPlugin("IdentifiedVisitor");
}).call(window);;(function(){var dfltPluginCfg={"urlKeyword":"","urlResultPageNumber":"","urlResultPosition":""};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.InternalSearch=function(a){var f={};a.configPlugin("InternalSearch",dfltPluginCfg||{},function(a){f=a});var l=function(d){var f={np:"undefined"!==typeof d.resultPageNumber?d.resultPageNumber:"1",click:"IS"};d.hasOwnProperty("keyword")&&(f.mc=d.keyword);d.hasOwnProperty("resultPosition")&&(f.mcrg=d.resultPosition);a.sendHit(f,[["hitType",["InternalSearch"]]])};a.internalSearch={};a.internalSearch.set=this.set=function(d){var f={},h=f;d.hasOwnProperty("keyword")&&(h.keyword=
d.keyword);h=f;d.hasOwnProperty("resultPageNumber")&&(h.resultPageNumber=d.resultPageNumber);d=a.getContext("InternalSearch")||{};f=ATInternet.Utils.completeFstLevelObj(f,d);"undefined"===typeof f.resultPageNumber&&(f.resultPageNumber="1");a.setContext("InternalSearch",f)};a.internalSearch.send=this.send=function(d){var f=!0;a.plugins.exec("TechClicks","manageClick",[d.elem,d.event,d.callback],function(a){f=a});l(d);return f};a.plugins.waitForDependencies(["Utils"],function(){var d;if(f.urlKeyword){var k=
document.location.href;d={};a.plugins.exec("Utils","getQueryStringValue",[f.urlKeyword,k],function(h){h&&(d.keyword=h);f.urlResultPageNumber&&a.plugins.exec("Utils","getQueryStringValue",[f.urlResultPageNumber,k],function(a){d.resultPageNumber=a||"1"})})}d&&a.setContext("InternalSearch",d);a.emit("InternalSearch:Ready",{lvl:"INFO",details:{config:{urlKeyword:f.urlKeyword,urlResultPageNumber:f.urlResultPageNumber},url:k,data:d}})})};window.ATInternet.Tracker.addPlugin("InternalSearch");
}).call(window);;(function(){var dfltPluginCfg={};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.MvTesting=function(a){var f=0,l=function(a,b){var e="";a.hasOwnProperty(b)&&(e=a[b],e=void 0===e?"":e+"");return e},d=function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},k=function(a){return"object"===typeof a&&!(a instanceof Array)},h=function(d){var b=d.name;a.exec("Utils","manageChapters",[d,"chapter",3],function(a){b=a+(b?b:"")});return b};a.mvTesting={};a.mvTesting.set=function(g){if(k(g)&&!d(g)){a.dispatchSubscribe("mvTesting");var b=l(g,"test"),
e=l(g,"waveId");g=l(g,"creation");a.setParam("abmvc",b+"-"+e+"-"+g,{hitType:["mvtesting"]})}};a.mvTesting.add=function(g){if(k(g)&&!d(g)){a.dispatchSubscribe("mvTesting");var b=l(g,"variable");g=l(g,"version");f++;a.setParam("abmv"+f,b+"-"+g,{hitType:["mvtesting"]})}};a.mvTesting.onDispatch=function(){var d=a.getContext("page")||{};a.setParam("p",h(d),{hitType:["mvtesting"]});a.setParam("s2",d.level2||"",{hitType:["mvtesting"]});a.setParam("type","mvt",{hitType:["mvtesting"]});a.sendHit(null,[["hitType",
["mvtesting"]]])}};window.ATInternet.Tracker.addPlugin("MvTesting");
}).call(window);;(function(){var dfltPluginCfg={};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.OnSiteAds=function(a){var f="",l=function(b){var c=b.name;a.exec("Utils","manageChapters",[b,"chapter",3],function(a){c=a+(c?c:"")});return c},d=function(a,b){return a[b]?a[b]:""},k=function(a,b){var c=d(a,b);if(c){var e=d(a,"prefix");if(c.campaignId){var e=e||"PUB",g=d(c,"campaignId"),f=d(c,"creation"),h=d(c,"variant"),k=d(c,"format"),l=d(c,"generalPlacement"),v=d(c,"detailedPlacement"),x=d(c,"advertiserId"),c=d(c,"url");return e+"-"+g+"-"+f+"-"+h+"-"+k+"-"+l+"-"+
v+"-"+x+"-"+c}if(c.adId)return e=e||"INT",g=d(c,"adId"),f=d(c,"format"),c=d(c,"productId"),e+"-"+g+"-"+f+"||"+c}},h=function(b){var c=a.getContext("page")||{};a.sendHit({atc:k(b,"click"),type:"AT",patc:l(c),s2atc:c.level2||"",stc:b.customObject||""},[["hitType",["onSiteAdsClick"]]])},g=function(b){a.sendHit({ati:k(b,"impression"),type:"AT",stc:b.customObject||""},[["hitType",["onSiteAdsImpression"]]])},b=function(b,c){var e=a.buffer.get("ati",!0)||{};e.value="string"===typeof e.value?[e.value]:e.value||
[];e.options=e.options||{hitType:[c,"page"]};e.value.push(b);a.buffer.set("ati",e.value,e.options)},e=function(b,c){b.click?a.setParam("atc",k(b,"click"),{hitType:[c,"page"]}):b.impression&&a.setParam("ati",k(b,"impression"),{hitType:[c,"page"]});if(b.customObject){a.setContext("onsiteads",{customObject:b.customObject});var e=a.getContext("page")||{};e.customObject=ATInternet.Utils.completeFstLevelObj(e.customObject,b.customObject,!1);a.setContext("page",e)}a.dispatchSubscribe("onSiteAds")};a.selfPromotion=
this.selfPromotion={};a.publisher=this.publisher={};a.publisher.set=this.publisher.set=function(a){e(a,"publisher")};a.selfPromotion.set=this.selfPromotion.set=function(a){e(a,"selfPromotion")};a.publisher.add=this.publisher.add=function(c){b(k(c,"impression"),"publisher");a.dispatchSubscribe("onSiteAds")};a.selfPromotion.add=this.selfPromotion.add=function(c){b(k(c,"impression"),"selfPromotion");a.dispatchSubscribe("onSiteAds")};var c=this.advertEvent=function(b){var c=!0;a.exec("TechClicks","manageClick",
[b.elem,b.event,b.callback],function(a){c=a});b.click?h(b):b.impression&&g(b);return c};a.publisher.send=this.publisher.send=function(a){return c(a)};a.selfPromotion.send=this.selfPromotion.send=function(a){return c(a)};a.onSiteAds={};a.onSiteAds.onDispatch=this.onDispatch=function(){if(!a.dispatchSubscribed("page")){var b=a.getContext("page")||{};a.setParam("type","AT",{hitType:["publisher","selfPromotion"]});a.getParam("atc")&&(a.setParam("patc",l(b),{hitType:["publisher","selfPromotion"]}),a.setParam("s2atc",
b.level2||"",{hitType:["publisher","selfPromotion"]}));(b=a.getContext("onsiteads"))&&b.customObject&&a.setParam("stc",b.customObject,{encode:!0,hitType:["publisher","selfPromotion"]});a.sendHit(null,[["hitType",["publisher","selfPromotion"]]])}};a.plugins.waitForDependencies(["Utils","TechClicks"],function(){f=document.location.href;a.plugins.exec("Utils","getQueryStringValue",["xtatc",f],function(b){b&&a.setParam("atc",b,{hitType:["publisher","selfPromotion","page"]})});a.emit("OnSiteAds:Ready",
{lvl:"INFO",details:{href:f}})})};window.ATInternet.Tracker.addPlugin("OnSiteAds");
}).call(window);;(function(){var dfltPluginCfg={};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Page=function(a){var f=["pageId","chapterLabel","update"],l=["pid","pchap","pidt"],d=["page","site"],k=["f","x"],h=function(b){var c=b.name;a.exec("Utils","manageChapters",[b,"chapter",3],function(a){c=a+(c?c:"")});return c},g=function(a,b,c){b?a=b:a||"undefined"===typeof c||(a=c);return a},b=function(a,b,c){b.hasOwnProperty(c)&&(a[c]=g(a[c],b[c]))},e=function(b){if(!ATInternet.Utils.isPreview()||a.getConfig("preview"))ATInternet.Utils.isPrerender(function(a){b(a)})||
b()},c=function(b,c,e){if(c)for(var g=0;g<d.length;g++)if(c.hasOwnProperty(d[g])&&c[d[g]])for(var f in c[d[g]])c[d[g]].hasOwnProperty(f)&&(e?b[k[g]+f]=c[d[g]][f]:a.setParam(k[g]+f,c[d[g]][f]))},n=function(b,c,e){if(c){a.exec("Utils","manageChapters",[c,"chapter",3],function(a){a&&(c.chapterLabel=a.replace(/::$/gi,""))});for(var d=0;d<l.length;d++)c.hasOwnProperty(f[d])&&(e?b[l[d]]=c[f[d]]:a.setParam(l[d],c[f[d]]))}},s=function(b,c,e){if(c&&c.keywords instanceof Array){var d=c.keywords.length;if(0<
d){for(var g="",f=0;f<d;f++)g+="["+c.keywords[f]+"]"+(f<d-1?"|":"");e?b.tag=g:a.setParam("tag",g)}}},q=function(b,c,e){if(c){var d,g=function(a){return a?a:"0"};d=""+(g(c.category1)+"-");d+=g(c.category2)+"-";d+=g(c.category3);e?b.ptype=d:a.setParam("ptype",d)}},m=function(b,c,e){if(c)for(var d in c)c.hasOwnProperty(d)&&"undefined"!==typeof c[d]&&(e?b[d]=c[d]:a.setParam(d,c[d]))};a.customVars=this.customVars={};a.customVars.set=this.customVars.set=function(b){var c=a.getContext("page")||{},e=c.customVars;
if(e){if(b)for(var d in b)b.hasOwnProperty(d)&&(e[d]=ATInternet.Utils.completeFstLevelObj(e[d],b[d],!0))}else e=b;c.customVars=e;a.setContext("page",c)};a.dynamicLabel=this.dynamicLabel={};a.dynamicLabel.set=this.dynamicLabel.set=function(b){var c=a.getContext("page")||{};c.dynamicLabel=ATInternet.Utils.completeFstLevelObj(c.dynamicLabel,b,!0);a.setContext("page",c)};a.tags=this.tags={};a.tags.set=this.tags.set=function(b){var c=a.getContext("page")||{};c.tags=ATInternet.Utils.completeFstLevelObj(c.tags,
b,!0);a.setContext("page",c)};a.customTreeStructure=this.customTreeStructure={};a.customTreeStructure.set=this.customTreeStructure.set=function(b){var c=a.getContext("page")||{};c.customTreeStructure=ATInternet.Utils.completeFstLevelObj(c.customTreeStructure,b,!0);a.setContext("page",c)};a.page={};a.page.reset=this.reset=function(){a.setContext("page",void 0)};a.page.set=this.set=function(c){a.dispatchSubscribe("page");var e=a.getContext("page")||{};e.name=g(e.name,c.name,"");e.level2=g(e.level2,
c.level2,"");b(e,c,"chapter1");b(e,c,"chapter2");b(e,c,"chapter3");e.customObject=ATInternet.Utils.completeFstLevelObj(e.customObject,c.customObject,!0);a.setContext("page",e)};a.page.send=this.send=function(d){var f={p:h(d),s2:d.level2||""},k=!0,l=d.customObject;if(l){var r=a.getParam("stc",!0);if(r&&r.options.permanent){var v=r?r.options.hitType:[],x=ATInternet.Utils.arrayIndexOf;if(-1!=x(v,"page")||-1!=x(v,"all"))l=ATInternet.Utils.completeFstLevelObj(r.value||{},l,!0)}a.exec("Utils","customObjectToString",
[l],function(a){f.stc=a})}l=a.getContext("page")||{};l.vrn&&(f.vrn=l.vrn,l.vrn=void 0,a.setContext("page",l));r=a.getContext("InternalSearch")||{};"undefined"!=typeof r.keyword&&(f.mc=ATInternet.Utils.cloneSimpleObject(r.keyword),"undefined"!=typeof r.resultPageNumber&&(f.np=ATInternet.Utils.cloneSimpleObject(r.resultPageNumber)),a.setContext("InternalSearch",void 0));ATInternet.Utils.isPreview()&&a.getConfig("preview")&&(f.pvw=1);c(f,d.customVars,!0);n(f,d.dynamicLabel,!0);s(f,d.tags,!0);q(f,d.customTreeStructure,
!0);r=a.getContext("campaigns")||{};m(f,r,!0);a.setContext("campaigns",void 0);a.exec("TechClicks","manageClick",[d.elem,d.event,d.callback],function(a){k=a});e(function(){a.sendHit(f)});l.name=g(l.name,d.name,"");l.level2=g(l.level2,d.level2,"");b(l,d,"chapter1");b(l,d,"chapter2");b(l,d,"chapter3");a.setContext("page",l);return k};a.page.onDispatch=this.onDispatch=function(){var b=a.getContext("page")||{},d=a.getContext("InternalSearch")||{};a.setParam("p",h(b));a.setParam("s2",b.level2||"");b.vrn&&
(a.setParam("vrn",b.vrn),b.vrn=void 0,a.setContext("page",b));"undefined"!=typeof d.keyword&&(a.setParam("mc",ATInternet.Utils.cloneSimpleObject(d.keyword)),"undefined"!=typeof d.resultPageNumber&&a.setParam("np",ATInternet.Utils.cloneSimpleObject(d.resultPageNumber)),a.setContext("InternalSearch",void 0));ATInternet.Utils.isPreview()&&a.getConfig("preview")&&a.setParam("pvw",1);c(null,b.customVars,!1);n(null,b.dynamicLabel,!1);s(null,b.tags,!1);q(null,b.customTreeStructure,!1);d=a.getContext("campaigns")||
{};m(null,d,!1);a.setContext("campaigns",void 0);var b=b.customObject,g=[["hitType",["page"]]];if(b)if(d=a.getParam("stc",!0)){var f=d.options.hitType||[],k=ATInternet.Utils.arrayIndexOf,k=-1!=k(f,"page")||-1!=k(f,"all"),f=d.options.permanent;k?(k=ATInternet.Utils.cloneSimpleObject(d),k.value=ATInternet.Utils.completeFstLevelObj(k.value||{},b,!0),a.setParam("stc",k.value,{encode:!0}),e(function(){a.sendHit(null,g)}),f&&a.setParam("stc",d.value,d.options)):(a.setParam("stc",b,{encode:!0}),e(function(){a.sendHit(null,
g)}),a.setParam("stc",d.value,d.options))}else a.setParam("stc",b,{encode:!0}),e(function(){a.sendHit(null,g)});else e(function(){a.sendHit(null,g)})}};window.ATInternet.Tracker.addPlugin("Page");
}).call(window);;(function(){var dfltPluginCfg={};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.SalesTracker=function(a){var f=function(b,e,c){b.hasOwnProperty(c)&&(b=b[c],a.setParam(e,void 0===b?"":b+"",{hitType:["page"]}))},l=function(a){for(var e in a)if(a.hasOwnProperty(e))return!1;return!0},d=function(a){return"object"===typeof a&&!(a instanceof Array)},k=function(b){var e="";a.exec("Utils","manageChapters",[b,"category",6],function(a){a&&(e=a)});e+=b.productId;b=a.getContext("product")||{};b.viewedProducts?b.viewedProducts.push(e):b.viewedProducts=[e];
a.setContext("product",b)},h=0,g=function(b){var e=b.productId?b.productId:"",c=b.category?b.category+"::":"";a.exec("Utils","manageChapters",[b,"category",6],function(a){a&&(c=a)});return c+e};a.order=this.order={};a.cart=this.cart={};a.aisle=this.aisle={};a.salesTracker={};a.product=this.product={};a.order.set=this.order.set=function(b){var e=!1;if(d(b)&&!l(b)){e=!0;a.dispatchSubscribe("page");a.dispatchSubscribe("salesTracker");f(b,"cmd","orderId");f(b,"roimt","turnover");f(b,"st","status");"boolean"===
typeof b.newCustomer?a.setParam("newcus",b.newCustomer?"1":"0",{hitType:["page"]}):b.newCustomer&&"undefined"===typeof a.getParams("newcus")&&a.setParam("newcus","0",{hitType:["page"]});var c=b.amount;d(c)&&(f(c,"mtht","amountTaxFree"),f(c,"mtttc","amountTaxIncluded"),f(c,"tax","taxAmount"));c=b.delivery;d(c)&&(f(c,"fp","shippingFeesTaxIncluded"),f(c,"fpht","shippingFeesTaxFree"),f(c,"dl","deliveryMethod"));f(b,"mp","paymentMethod");c=b.discount;d(c)&&(f(c,"dsc","discountTaxIncluded"),f(c,"dscht",
"discountTaxFree"),f(c,"pcd","promotionalCode"));"boolean"===typeof b.confirmationRequired?a.setParam("tp",b.confirmationRequired?"pre1":"",{hitType:["page"]}):b.confirmationRequired&&"undefined"===typeof a.getParams("tp")&&a.setParam("tp","",{hitType:["page"]});b=b.orderCustomVariables;if(b instanceof Array)for(c=0;c<b.length;c++)f(b,"o"+(c+1),c)}return e};a.cart.set=this.cart.set=function(b){var e=!1;d(b)&&!l(b)&&(e=!0,a.dispatchSubscribe("page"),a.dispatchSubscribe("salesTracker"),f(b,"idcart",
"cartId"),"boolean"===typeof b.isBasketPage?"pre1"!==a.getParams("tp")&&a.setParam("tp",b.isBasketPage?"cart":"",{hitType:["page"]}):b.isBasketPage&&"undefined"===typeof a.getParams("tp")&&a.setParam("tp","",{hitType:["page"]}));return e};a.cart.add=this.cart.add=function(b){var e=!1;if(d(b)&&!l(b)&&(e=!0,b=b.product,d(b))){h++;var c=h,k=g(b);a.setParam("pdt"+c,k,{hitType:["page"]});f(b,"qte"+c,"quantity");f(b,"mt"+c,"unitPriceTaxIncluded");f(b,"mtht"+c,"unitPriceTaxFree");f(b,"dsc"+c,"discountTaxIncluded");
f(b,"dscht"+c,"discountTaxFree");f(b,"pcode"+c,"promotionalCode")}return e};a.aisle.set=this.aisle.set=function(b){var e=!1;if(d(b)&&!l(b)){e=!0;a.dispatchSubscribe("page");var c="";a.exec("Utils","manageChapters",[b,"level",6],function(a){c=a});c=c.replace(/::$/gi,"");a.setParam("aisl",c,{hitType:["page"]})}return e};a.product.add=this.product.add=function(b){var e=!1,c;if(c=d(b))if(c=!l(b)){a:{c=["productId"];for(var g=0;g<c.length;g++)if(void 0===b[c[g]]){c=!0;break a}c=!1}c=!c}c&&(e=!0,k(b),a.dispatchSubscribe("salesTracker"));
return e};a.salesTracker.onDispatch=this.onDispatch=function(){a.getParams("cmd");a.getParams("idcart")||"cart"!==a.getParams("tp")&&a.getParams("tp");var b=a.getContext("product");b&&b.viewedProducts&&0<b.viewedProducts.length&&(a.setParam("pdtl",b.viewedProducts.join("|"),{hitType:["product"]}),a.setParam("type","pdt",{hitType:["product"]}),a.sendHit(null,[["hitType",["product"]]]))}};window.ATInternet.Tracker.addPlugin("SalesTracker");
}).call(window);;(function(){var dfltPluginCfg={"clicksAutoManagementEnabled":true,"clicksAutoManagementTimeout":500};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.TechClicks=function(a){var f,l;a.configPlugin("TechClicks",dfltPluginCfg||{},function(a){f=a.clicksAutoManagementEnabled;l=a.clicksAutoManagementTimeout});this.deactivateAutoManagement=function(){f=!1};var d=function(a){switch(a.target){case "_top":window.top.location.href=a.url;break;case "_parent":window.parent.location.href=a.url;break;default:window.location.href=a.url}},k=function(a){var b=a.timeout;a.mailto?setTimeout(function(){window.location.href=a.mailto},
b):a.form?setTimeout(function(){a.form.submit()},b):a.url&&setTimeout(function(){d({url:a.url,target:a.target})},b)},h=function(b){for(var e,g="_self",f=b.timeoutonly;b;){if(b.href&&0===b.href.indexOf("http")){e=b.href.split('"').join('\\"');g=b.target?b.target:g;break}b=b.parentNode}if(e){if(!f)a.onTrigger("Tracker:Hit:Sent:Ok",function(){d({url:e,target:g})});k({url:e,target:g,timeout:l})}},g=function(b){var e=b;for(b=e.timeoutonly;e&&"FORM"!==e.nodeName;)e=e.parentNode;if(e){if(!b)a.onTrigger("Tracker:Hit:Sent:Ok",
function(){e.submit()});k({form:e,timeout:l})}},b=function(b){var e=b;for(b=e.timeoutonly;e&&!(e.href&&0<=e.href.indexOf("mailto:"));)e=e.parentNode;if(e){if(!b)a.onTrigger("Tracker:Hit:Sent:Ok",function(){window.location.href=e.href});k({mailto:e.href,timeout:l})}},e=function(a){for(;a;){if(a.href){if(0<=a.href.indexOf("mailto:"))return"mailto";if(0===a.href.indexOf("http"))return"redirection"}else if("FORM"===a.nodeName)return"form";a=a.parentNode}return!1};this.manageClick=function(a,d,k){var l=
!0;if(f&&a){var m;a:{for(m=a;m;){if("function"===typeof m.getAttribute&&("_blank"===m.getAttribute("target")||"no"===m.getAttribute("data-atclickmanagement"))){m=!0;break a}m=m.parentNode}m=a;for(var p=window.location.href,u;m;){if((u=m.href)&&0<u.indexOf("#")&&p.substring(0,0<p.indexOf("#")?p.indexOf("#"):p.length)===u.substring(0,u.indexOf("#"))){m=!0;break a}m=m.parentNode}m=!1}p=e(a);if(!m&&p)switch(p){case "mailto":b(a);l=!1;break;case "form":g(a);l=!1;break;case "redirection":h(a),l=!1}}d&&
(a=d.defaultPrevented,"function"===typeof d.isDefaultPrevented&&(a=d.isDefaultPrevented()),a||d.preventDefault&&d.preventDefault());k&&k();return l}};window.ATInternet.Tracker.addPlugin("TechClicks");
}).call(window);;(function(){var dfltPluginCfg={};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Utils=function(a){var f=this,l={};f.getQueryStringValue=function(a,d){var g=window.ATInternet.Utils.hashcode(d).toString();if(!l[g]){l[g]={};var b=RegExp("[&#?]{1}([^&=#?]*)=([^&#]*)?","g"),e=b.exec(d);if(null!==e)for(;null!==e;)l[g][e[1]]=e[2],e=b.exec(d)}return l[g].hasOwnProperty(a)?l[g][a]:null};f.customObjectToString=function(a){return encodeURIComponent(window.ATInternet.Utils.jsonSerialize(a))};f.manageChapters=function(d,f,g){var b=a.getConfig("ignoreEmptyChapterValue"),
e="";if(d){g=parseInt(g,10);for(var c=1;c<g+1;c++)var l=d[f+c]||"",e=b?e+(l?l+"::":""):e+(d.hasOwnProperty(f+c)?l+"::":"")}return e};f.getDocumentLevel=function(){var d=a.getConfig("documentLevel");if(0>d.indexOf("."))return window[d]||document;d=d.split(".");return window[d[0]][d[1]]||document};f.getLocation=function(){return f.getDocumentLevel().location.href};a.dispatchIndex={};a.dispatchStack=[];a.dispatchEventFor={};var d=0;a.dispatchSubscribe=function(d){return a.dispatchIndex[d]?!1:(a.dispatchStack.push(d),
a.dispatchIndex[d]=!0)};a.dispatchSubscribed=function(d){return!0===a.dispatchIndex[d]};a.addSpecificDispatchEventFor=function(f){return a.dispatchEventFor[f]?!1:(a.dispatchEventFor[f]=!0,d++,!0)};a.processSpecificDispatchEventFor=function(f){a.dispatchEventFor[f]&&(a.dispatchEventFor[f]=!1,d--,0===d&&(a.dispatchEventFor={},a.emit("Tracker:Plugin:SpecificEvent:Exec:Complete",{lvl:"INFO"})))};a.dispatch=function(){var f=function(){for(;0<a.dispatchStack.length;){var d=a.dispatchStack.pop();a[d].onDispatch()}a.dispatchIndex=
{};a.delContext(void 0,"customObject")},h=function(){if(a.plugins.isExecWaitingLazyloading())a.onTrigger("Tracker:Plugin:Lazyload:Exec:Complete",function(){f()},!0);else f()};if(0===d)h();else a.onTrigger("Tracker:Plugin:SpecificEvent:Exec:Complete",function(){h()},!0)};a.dispatchRedirect=function(d){var f=!0;d&&d.elem&&(d.elem.timeoutonly=!0,a.plugins.exec("TechClicks","manageClick",[d.elem,d.event,d.callback],function(a){f=a}));a.dispatch();return f}};window.ATInternet.Tracker.addPlugin("Utils");
}).call(window);;(function(){var dfltPluginCfg={};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.RichMedia=function(a){var f=new function(){this._timeout={};this.setTimeout=function(b,e,c){this._timeout[b]=this._timeout[b]||{};this._timeout[b][e]=window.setTimeout(function(){a.richMedia.send({action:"refresh",playerId:b,mediaLabel:e})},1E3*c)};this.setTimeoutObject=function(b,e,c){this._timeout[b]=this._timeout[b]||{};if("undefined"===typeof this._timeout[b][e]){var d=[],f;for(f in c)c.hasOwnProperty(f)&&d.push({delay:g(f,0),refresh:g(c[f],5)});d.sort(function(a,
b){return a.delay<b.delay?-1:a.delay>b.delay?1:0});this._timeout[b][e]={arrObj:d}}c=this._timeout[b][e];if(0<c.arrObj.length&&(d=c.arrObj[0].delay,f=c.arrObj[0].refresh,"number"===typeof d&&"number"===typeof f&&0<f)){c[d]=c[d]||{};var h=void 0;"undefined"!==typeof c.arrObj[1]&&(h=c.arrObj[1].delay);var k=0;"undefined"===typeof h?k=1:"number"===typeof c[d].num?k=Math.max(c[d].num-1,0):"number"===typeof h&&(k=Math.floor(60*(h-d)/f));c[d].num=k;0<k?c[d].timeout=window.setTimeout(function(){a.richMedia.send({action:"refresh",
playerId:b,mediaLabel:e})},1E3*f):"undefined"!==typeof c[d].timeout&&(window.clearTimeout(c[d].timeout),c[d].timeout=void 0,c.arrObj.splice(0,1),window.setTimeout(function(){a.richMedia.send({action:"refresh",playerId:b,mediaLabel:e})},1E3*f));this._timeout[b][e]=c}};this.clearTimeout=function(a,d){this._timeout[a]=this._timeout[a]||{};if("object"===typeof this._timeout[a][d])for(var c in this._timeout[a][d]){if(this._timeout[a][d].hasOwnProperty(c)){var f=this._timeout[a][d][c].num;"undefined"!==
typeof f&&0<f&&(window.clearTimeout(this._timeout[a][d][c].timeout),this._timeout[a][d][c].timeout=void 0)}}else window.clearTimeout(this._timeout[a][d])};this.removePlayer=function(b){for(var d in this._timeout[b])this._timeout[b].hasOwnProperty(d)&&(this.clearTimeout(b,d),a.richMedia.send({action:"stop",playerId:b,mediaLabel:d}));this._timeout[b]={}};this.removeAll=function(){for(var a in this._timeout)this._timeout.hasOwnProperty(a)&&this.removePlayer(a);this._timeout={}}},l=new function(){this._media=
function(){this.m9=this.m6=this.m5=this.m1=this.rfsh=this.buf=this.a=this.p=this.clnk=this.s2=this.plyr=this.type=""};this._mediaAll={};this.setMediaProperty=function(a,d,c,f){this._mediaAll[a]=this._mediaAll[a]||{};this._mediaAll[a][d]=this._mediaAll[a][d]||new this._media;this._mediaAll[a][d][c]=f};this.getMediaProperty=function(a,d,c){return this._mediaAll[a]&&this._mediaAll[a][d]?this._mediaAll[a][d][c]:""};this.removePlayer=function(a){this._mediaAll[a]={}};this.removeAll=function(){this._mediaAll=
{}}},d=function(b,d,c){var f=b[c]||"";a.exec("Utils","manageChapters",[b,d,3],function(a){f=a+f});return f},k=function(a,d,c,f){"boolean"===typeof a[d]&&a[d]&&(c=f);return c},h=function(a){var d=0;/^(\-|\+)?([0-9]+)$/.test(a)&&(d=Number(a));return d},g=function(a,d){var c=parseInt(a,10);return c?Math.max(c,d):0};a.richMedia={};a.richMedia.add=this.add=function(a){a=a||{};var e=h(a.playerId),c=d(a,"mediaTheme","mediaLabel"),f=k(a,"isBuffering","0","1"),g=k(a,"isEmbedded","int","ext");l.setMediaProperty(e,
c,"plyr",e);l.setMediaProperty(e,c,"type",a.mediaType||"");l.setMediaProperty(e,c,"s2",a.mediaLevel2||"");l.setMediaProperty(e,c,"p",c);l.setMediaProperty(e,c,"clnk",a.previousMedia||"");l.setMediaProperty(e,c,"a",a.action||"");l.setMediaProperty(e,c,"buf",f);l.setMediaProperty(e,c,"rfsh",a.refreshDuration||"");l.setMediaProperty(e,c,"m1",a.duration||"");l.setMediaProperty(e,c,"m5",g);l.setMediaProperty(e,c,"m6",a.broadcastMode||"");l.setMediaProperty(e,c,"m9",a.webdomain||"")};a.richMedia.remove=
this.remove=function(a){f.removePlayer(a);l.removePlayer(a)};a.richMedia.removeAll=this.removeAll=function(){f.removeAll();l.removeAll()};a.richMedia.send=this.send=function(b){b=b||{};var e=h(b.playerId),c=d(b,"mediaTheme","mediaLabel"),n={},s=k(b,"isBuffering","0","1");n.type=l.getMediaProperty(e,c,"type");n.plyr=e;n.p=c;n.a=b.action||"";n.s2=l.getMediaProperty(e,c,"s2");n.m1=l.getMediaProperty(e,c,"m1");n.m5=l.getMediaProperty(e,c,"m5");n.m6=l.getMediaProperty(e,c,"m6");if("play"===n.a||"info"===
n.a)n.buf=s,b=a.getContext("page")||{},n.prich=d(b,"chapter","name"),n.s2rich=b.level2||"",n.clnk=l.getMediaProperty(e,c,"clnk"),n.m9=encodeURIComponent(l.getMediaProperty(e,c,"m9"));a.sendHit(n,[["hitType",["richmedia"]]]);"pause"!==n.a&&"stop"!==n.a||f.clearTimeout(e,c);if("play"===n.a||"refresh"===n.a)n=l.getMediaProperty(e,c,"rfsh"),"object"===typeof n?f.setTimeoutObject(e,c,n):(n=g(n,5),0!==n&&f.setTimeout(e,c,n))}};window.ATInternet.Tracker.addPlugin("RichMedia");
}).call(window);if(typeof window.ATInternet.onTrackerLoad==='function'){window.ATInternet.onTrackerLoad();}